//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public long id_categoria { get; set; }
        public string nombre { get; set; }
        public byte portada { get; set; }
        public byte hide { get; set; }
    }
}
