//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Noticia
    {
        public long id_noticia { get; set; }
        public long id_categoria { get; set; }
        public string titulo { get; set; }
        public string subtitulo { get; set; }
        public string descripcion { get; set; }
        public string foto_portada { get; set; }
        public string foto_noticia { get; set; }
        public byte portada { get; set; }
        public byte hide { get; set; }
        public System.DateTime date { get; set; }
        public string video_noticia { get; set; }
    }
}
