//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace News.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portada
    {
        public int id_portada { get; set; }
        public int cantidad { get; set; }
        public long latest { get; set; }
        public long latestr { get; set; }
        public string nombre { get; set; }
        public int igual { get; set; }
    }
}
